# The secrets file should not be checked into Git. It's published only for demonstration purpose.
secretGenerator:
  - name: mysql-root-pass
    literals:
      - password=root
  - name: mysql-user-pass
    literals:
      - username=root
      - password=root
  - name: mysql-db-url
    literals:
      - database=polls
      - url=jdbc:mysql://localhost:3306/tickets?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
resources:
  - tickets-deployment.yaml