apiVersion: v1                # API version
kind: Service                 # Type of the kubernetes resource
metadata:
  name: tickets-service    # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: tickets-app
spec:
  type: ClusterIP              # The service will be exposed by opening a Port on each node and proxying it.
  selector:
    app: tickets-app          # The service exposes Pods with label `app=polling-app-server`
  ports:                      # Forward incoming connections on port 8080 to the target port 8080
    - name: http
      port: 8080
      targetPort: 8080
    - name: mysql
      port: 49196
      targetPort: 3306
